Backend/Controllers/userController.js, Backend/Routers/userRouter.js
Fixed the issue in the EmailVerify component where the sendOTP API was not working. The problem was caused by:
A missing route for sendOTP in userRouter
A missing sendOTP function in userController
I have added the necessary route and implemented the controller function. The email verification flow is now working as expected.
=> Update Emailverify function,Route

Backend/Controllers/userController.js, Backend/utils/deleteUplodedFile.js
Create a function to delete uploaded files and remove existing files when new ones are uploaded in the following operations: Update User, Update CV, and Update Image.
=> Update user bugfix

Backend/Controllers/adminController.js
Fixed these bugs in 3 functionalities:
1. Registration of Admin
2. Update admin user details
3. Admin login & logout
=> Admin backend bugfix&clean

Backend/middlewares/fileUploading.js
=> Create relavant folder

GR_Admin_frontend/src/components/Jobs/CandidateDetailsView.jsx
The issue has been with how the front-end expected the jobs and how they were returned from the backend (data.data expected but data.jobs is what returned) + alignment issues with the dropdown (fixed in the frontend)
=> View application by job id - Bug Fix

Admin_Frontend/src/pages/Login.tsx
change port number and add some validations for invalid credentials
=> Login Bug Fix in Frontend

Backend/Controllers/adminController.js
when admin update a profile image, older one was still in the server causing storage issues.
It was fixed with the help of @DilanMadushan's deleteUploadedFile util.
=> admin older pfp isn't getting removed bug fix

Backend/Controllers/blogController.js
According to the front-end change blog controller update function.
=> update blogController:BugFix_according to frontend

Admin_Frontend/src/pages/Workshop/AddWorkshop.tsx, Backend/Controllers/workshopsController.js, Backend/package-lock.json
Fix SQl query in back end  -createworkshop
=> Add workshop -backend

GR_Admin_frontend/src/pages/Blog/EditBlog.jsx
change and fix editBlogs in GR-Amin according to backend
=> EditBlogs:BugFix_edit and update

Backend/Controllers/blogController.js
Missing message: Blog not found. in delete function
=> update the message_BlogController

Backend/Controllers/workshopsController.js
The image hasn't included as the values
=> workshop doesn't update backend bug fix 

Admin_Frontend/src/pages/Admin/AddAdmin.tsx
add new admin part is done with validations
=> add new admin part is done

GR_Admin_frontend/src/pages/BlogManagement.jsx
Add a function to the blog delete on Blog Management in the frontend
=> BlogManagemnet:BugFix_add_function

Admin_Frontend/src/pages/Workshop/AddWorkshop.tsx
Fixed the error in admin frontend while clicking publishworkshop button
=> fixed PublishWorkshop button-frontend

Backend/Controllers/blogController.js
Blog Controller update- for fetch Blog Comments
=> BlogController:BugFIx:fetchBlogComments

Backend/Controllers/workshopsController.js, Backend/Routers/workshopsRouter.js, GR_Admin_frontend/src/pages/Workshop/UpdateWorkshop.jsx
the issue was with how the data is stored in the database + the file was passed as json which caused too large payload
=> Admin workshop update frontend bugfix

GR_Admin_frontend/src/pages/BlogManagement.jsx
Fix the refresh button and fix the date in a blog post
=> BlogManagemnet_rontend:BugFix

Admin_Frontend/src/App.tsx, Admin_Frontend/src/components/Navbar.tsx, GR_Admin_frontend/src/App.jsx, GR_Admin_frontend/src/components/Navbar.jsx, GR_Admin_frontend/src/pages/Workshop/AddWorkshop.jsx
fix The GR_Admin_Frontend Publishfowrkshop
=> Gr admin publishworkhop fix

Backend/Controllers/blogController.js
Update blogControlelr_to to fetch likes, comments, and views. updated code
=> BlogController:BugFix-according to frontend

GR_Admin_frontend/src/pages/BlogManagement.jsx
=> BlogManagent:bugFix3

GR_Admin_frontend/src/pages/Admin/ViewAdmin.jsx
the issue has been with how the image was called as the path (incorrect folder structure)
=> Admin Image not showing bug fix

Admin_Frontend/src/pages/Dashboard.tsx
Remove all mock data from the Admin Dashboard and display actual values fetched from API endpoints
=> Admin dashboard bugfix

Backend/Controllers/blogController.js
Blog controller add author image part
=> BlogController:BugFix:add author

GR_Admin_frontend/src/pages/Admin/ViewAdmin.jsx, GR_Admin_frontend/src/pages/AdminUsers.jsx
axios wasn't sending the cookie
=> Admin Management bug fix

GR_Admin_frontend/src/components/Navbar.jsx
=> Remove settings & notifications

GR_Admin_frontend/src/components/Sidebar.jsx
the logout endpoint which clears the cookie is correctly called with credentials
=> logout functionality only for JWT frontend bug fix

Client_Frontend/src/Pages/Dashboard.jsx
Profile image does anot ppear in client dashboard - fix it and update CV part also
=> Dashboard-Client-BugFix- profile image and cv

Client_Frontend/src/components/dashboard/EditProfileForm.jsx
=> EditProfileForm:BugFix - fix the update user data

Client_Frontend/src/components/dashboard/AccountSettings.jsx
=> AccountSetting-BugFix- delete part

Backend/Controllers/AuthConttrollers/facebookAuthController.js, Backend/Controllers/AuthConttrollers/googleAuthController.js, Client_Frontend/src/Pages/BlogDetailsPage.jsx, Client_Frontend/src/Pages/BlogPage.jsx, Client_Frontend/src/Pages/Login.jsx, GR_Admin_frontend/.env, GR_Admin_frontend/src/components/EditAdmin.jsx, GR_Admin_frontend/src/components/JobDashboard.jsx, GR_Admin_frontend/src/components/Jobs/AddJob.jsx, GR_Admin_frontend/src/components/Jobs/CandidateDetailsView.jsx, GR_Admin_frontend/src/components/Jobs/EditJob.jsx, GR_Admin_frontend/src/components/Sidebar.jsx, GR_Admin_frontend/src/components/ViewClient.jsx, GR_Admin_frontend/src/config/baseUrlConfig.js, GR_Admin_frontend/src/pages/Admin/AddAdmin.jsx, GR_Admin_frontend/src/pages/Admin/ViewAdmin.jsx, GR_Admin_frontend/src/pages/AdminUsers.jsx, GR_Admin_frontend/src/pages/ApplicationDetailView.jsx, GR_Admin_frontend/src/pages/Blog/AddNewBlog.jsx, GR_Admin_frontend/src/pages/Blog/EditBlog.jsx, GR_Admin_frontend/src/pages/BlogManagement.jsx, GR_Admin_frontend/src/pages/ClientUsers.jsx, GR_Admin_frontend/src/pages/Dashboard.jsx, GR_Admin_frontend/src/pages/JobApplicationsView.jsx, GR_Admin_frontend/src/pages/Jobs.jsx, GR_Admin_frontend/src/pages/Login.jsx, GR_Admin_frontend/src/pages/Workshop/AddWorkshop.jsx, GR_Admin_frontend/src/pages/Workshop/UpdateWorkshop.jsx, GR_Admin_frontend/src/pages/Workshops.jsx
static localhost urls were removed and the urls were taken from a config file, that exports either the environment variable or the default link (localhost:8000)
=> Remove all static urls

Client_Frontend/src/components/dashboard/AccountSettings.jsx
The password change is not working. Fix the bug
=> AccountSetting:BugFix- fix the change password

Client_Frontend/src/Pages/Contact.jsx, Client_Frontend/src/Pages/Services.jsx
The FAQ button was not working.. It was fixed. Now it successfully navigates to the FAQ section.
=> Fix the FAQs button

GR_Admin_frontend/src/components/EditAdmin.jsx
withCredentials hasn't included
=> EditAdmin updated to send requests with credentials

Client_Frontend/src/Pages/Subsidiaries.jsx
=> Fixed the learn more button

Client_Frontend/src/Pages/Dashboard.jsx
Dashboard.jsx bug fix- client last active time doesnt work.
=> Dashborad,jsx-BugFix: last active time is not working

GR_Admin_frontend/src/components/Sidebar.jsx
there wern't any implementation
=> admin settings icon removal

Client_Frontend/src/Pages/WorkshopsAndSeminarsPage.jsx
Remove prize And View Details Button in workshop seminar past event
=> Removed button

Backend/Controllers/workshopsController.js, Client_Frontend/src/Pages/WorkshopsAndSeminarsPage.jsx
causing errors when adding a new workshop with fields like [link][description] and [event_type]..When Admin create workshop admin should add link to register...
=> Fixed the miss match of SQL query in create workshop

Client_Frontend/src/Pages/BlogPage.jsx
issue: logic hasn't been implemented.
=> client blog filter bugfix

Client_Frontend/src/Pages/Home.jsx, Client_Frontend/src/Pages/WorkshopsAndSeminarsPage.jsx
issue: image wasn't called specifying the correct path
=> workshop image not visible bug fix

Backend/Controllers/authController.js, Client_Frontend/src/Pages/Signup.jsx, Client_Frontend/src/Pages/VerifyEmail.jsx
Bub Fix: Client Register doesn't work, OTP verify doesn't work, & OTP not send correctly
=> Client_RegisterBug:fix

GR_Admin_frontend/src/pages/Workshop/AddWorkshop.jsx, GR_Admin_frontend/src/pages/Workshop/UpdateWorkshop.jsx, GR_Admin_frontend/src/pages/Workshops.jsx
Add a date picker to the date text box, and bug fix the fetch date and time
=> AddWorkshop:BugFix

Backend/Routers/jobApplicationRouter.js, Client_Frontend/src/Pages/Application.jsx
Fixed job application update and view issues
=> Appilcation:bugFix

Client_Frontend/src/components/dashboard/ProfileOverview.jsx
change update profile image edit UI.
=> ProfileOverview:Fix

GR_Admin_frontend/src/components/Jobs/CandidateDetailsView.jsx
implement the view resume function (button) to show the cv in the backend server
=> Add view resume functionality to candidate details

Backend/Routers/jobApplicationRouter.js, Client_Frontend/src/Pages/Application.jsx, GR_Admin_frontend/src/pages/JobApplicationsView.jsx
added 2 routers for user and admin for both add and delete cv functionalities. done as per a bug shown by testing team
=> Job application bug fix

Client_Frontend/src/Pages/Services.jsx
=> Services:BugFix

Client_Frontend/src/Pages/JobDetails.jsx
correct the job description doesn't fetch
=> JobDetails:bugFix

Client_Frontend/src/Pages/JobDetails.jsx
add optional chaining to responsibility, requirement and benifits for null fileds
=> add optional chaining

Backend/Controllers/JobsManagementController.js
job application records in the database had to be deleted because of the foreign key constraint with the job.
=> make job applications delete upon job deletion

Client_Frontend/src/Pages/JobListings.jsx
fixed error in location filter
=> JobListing:bug-Fix

Client_Frontend/src/Pages/WorkshopsAndSeminarsPage.jsx
Add and fix the functionality workshop share. Created a popup to share
=> fix share function workshop

GR_Admin_frontend/src/pages/Jobs.jsx
missing fileds added, json wasn't properly passed or stringyfied before sending backend are fixed
=> Editjob bugfix

Client_Frontend/src/Pages/BlogDetailsPage.jsx
add share functionality to share button for blog and fixed the related blog post not display
=> BlogDetails:BugFix and Add

GR_Admin_frontend/src/pages/ClientUsers.jsx
=> Refresh button fixing

Backend/Controllers/jobApplicationController.js, Backend/utils/deleteUplodedFile.js
job application on the server hasn't been deleted previously when deleting a job application, only the database record. it's fixed
=> made resume be deleted on deletion of job application

Client_Frontend/src/components/Navbar.jsx
fixed the issue when scroll page and open the menu error.
=> menu pop up issue fix

Client_Frontend/src/Pages/JobDetails.jsx
a proper error message hasn't been showed for duplicate entry error
=> Error handled on attempts to apply for same job

Client_Frontend/src/Pages/Login.jsx, GR_Admin_frontend/src/pages/InquiryManagement.jsx
The date hasn't been called from the inquiry object
=> Inquiry management date bug fix

Client_Frontend/src/Pages/Dashboard.jsx, Client_Frontend/src/components/Navbar.jsx
=> fix the nav bar

GR_Admin_frontend/src/pages/ClientUsers.jsx
=> add buttons

Backend/Controllers/authController.js
Updated the token expiration time. maxAge: 100 * 60 * 60 to maxAge: 60 * 60 * 1000,
=> updated the token expired time

GR_Admin_frontend/src/pages/ClientUsers.jsx
Client status was calculated to be shown as active if they have logged within 3 weeks.
=> Client status properly calculated in admin portal (updated)

GR_Admin_frontend/src/components/Sidebar.jsx
remove setting icon and  show scroll bar when minimize screen
=> updated side bar

Backend/Controllers/JobsManagementController.js, GR_Admin_frontend/src/components/Jobs/AddJob.jsx, GR_Admin_frontend/src/components/Jobs/EditJob.jsx, GR_Admin_frontend/src/pages/Jobs.jsx
According to new requirements, change the functionality to add and update. Remove some required fields.
=> update the job functions

GR_Admin_frontend/.env, GR_Admin_frontend/src/pages/Jobs.jsx
Added public view to the admin job view description in the client-side view
=> update admin job

Backend/Controllers/userController.js, Client_Frontend/src/components/Footer.jsx
fix the issues and add functionality, same user subscribe, non-registered user subscribe, without email
=> news letter subscription bug fix

Backend/Controllers/blogController.js, GR_Admin_frontend/src/components/Jobs/AddJob.jsx, GR_Admin_frontend/src/pages/Blog/EditBlog.jsx
Bugs fixed:
Author Image disappear after other images update.
Author image not previewing properly.
(in admin portal)
=> Edit blog bug fix

Client_Frontend/src/App.jsx, Client_Frontend/src/Pages/JobDetails.jsx, Client_Frontend/src/Pages/Login.jsx
Made the job details page visible for everyone and update the logic to show the application form (once clicked the 'apply for this position button') only for logged in users. Otherwise, redirect them to login and after logged in, back to the same job details page.
=> Enhance apply for job auth flow and login redirect

Backend/auth/googleAuth.js
=> google loging fixing

Backend/auth/googleAuth.js, Client_Frontend/src/Pages/WorkshopsAndSeminarsPage.jsx
remove place holders in workshop
=> Workshop photo fixing

Client_Frontend/src/Pages/JobDetails.jsx
instead of just a string separated by commas.
=> Make job details list items appear as list

Client_Frontend/src/Pages/Signup.jsx
add toast message to when user register with already given email address
=> add toast message same email error

Backend/Controllers/authController.js, Backend/Routers/authRouter.js, Client_Frontend/src/App.jsx, Client_Frontend/src/Pages/EmailCheck.jsx, Client_Frontend/src/Pages/ResetPassword.jsx, Client_Frontend/src/Pages/VerifyResetPassword.jsx
Add a new controller function to get otp for moving to add a new password.
=> forgot password bug fixed and update

Client_Frontend/src/Pages/About.jsx, Client_Frontend/src/Pages/Services.jsx
add Why choose gamage recruiters  section
=> Add why choose gamage recruiters section

Client_Frontend/src/Pages/About.jsx
1st issue from the given report
=> Update About page gr logo and location details

Client_Frontend/src/Pages/TrustedPartners.jsx, Client_Frontend/src/components/Patners/TestimonialsSection.jsx
Add two testimonials to the testimonial and trster partnet component
=> add two testimonial to testimonial

Client_Frontend/src/Pages/Contact.jsx
=> Fixed Website section

Client_Frontend/src/Pages/About.jsx
=> Vision mission bug fix

Client_Frontend/src/Pages/Contact.jsx
info@gamagerecruiters.lk
hr@gamagerecruiters.lk
=> Added two more contact details

Client_Frontend/src/Pages/JobListings.jsx
Add the lates job scroll part and and few styles
=> Change job page layout and styles

Client_Frontend/src/Pages/Services.jsx
=> Fixed feedback issue

Client_Frontend/src/Pages/Signup.jsx
- first  format SignUp page code with Prettier
- then add the validations
- checked the backend and successfully signed up
=> Add birth date validation to SignupPage

Client_Frontend/src/Pages/Dashboard.jsx, Client_Frontend/src/components/dashboard/ProfileOverview.jsx
- change the logout button position
- fix update cv button
=> Enhance UI in user dashboard profile section
